repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.3.0
    hooks:
      - id: gofmt
      - id: govet
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
